service:
  name: sso
  version: v1.0.0
server:
  http:
    address: 0.0.0.0:8002
    timeout: 10s
  grpc:
    address: 0.0.0.0:9002
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/edu_sso?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
reg:
  etcd:
    endpoints:
      - "119.27.191.44:2379"
    dialTimeout: 3s
jwt:
  # token 密钥，生产环境时及的修改
  secret: edu/admin
  # token 过期时间 单位：秒
  timeout: 7200s
  # 头
  header: Authorization
  #
  query: token
  # 
  cookie: jwt
