service:
  name: uuid
  version: v1.0.0
server:
  http:
    address: 0.0.0.0:8004
    timeout: 1s
  grpc:
    address: 0.0.0.0:9004
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/edu_sso?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
reg:
  etcd:
    endpoints:
      - "119.27.191.44:2379"
    dialTimeout: 3s
logger:
  # 日志存放路径
  path: ../../logs
  # 控制台日志
  stdout: true
  # 日志等级
  level: -1
  # 业务日志开关
  # enabledbus: false
  # 请求日志开关
  # enabledreq: false
  # 数据库日志开关 dev模式，将自动开启
  # enableddb: false
  # 自动任务日志开关 dev模式，将自动开启
  # enabledjob: false
app:
  uuid:
    # 机器ID
    machine_id: 1
