service:
  name: sys
  version: v1.0.0
server:
  http:
    address: 0.0.0.0:8007
    timeout: 10s
  grpc:
    address: 0.0.0.0:9007
    timeout: 10s
  middleware:
    jwt:
      # token 密钥，生产环境时及的修改
      secret: admin123456
      # token 过期时间 单位：秒
      timeout: 3600s
client:
  sso:
    dial: "10s"
    timeout: "10s"
    zone: "sh001"
    breaker:
      window: "3s"
      bucket: 10
      k: 1.5
      request: 20
data:
  admin:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/edu_sys?charset=utf8mb4&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
  migrate:
    path: file://../../migrations
reg:
  etcd:
    endpoints:
      - "119.27.191.44:2379"
    dialTimeout: 3s
  instance:
    zone: "sh001"
    env: "dev"
    hostname: "test1"
    appid: "service.sso"
    addrs:
      - "grpc://127.0.0.1:9102"
logger:
  # 日志存放路径
  path: temp/logs
  # 控制台日志
  # stdout: true
  # 日志等级
  # level: all
  # 业务日志开关
  # enabledbus: false
  # 请求日志开关
  # enabledreq: false
  # 数据库日志开关 dev模式，将自动开启
  # enableddb: false
  # 自动任务日志开关 dev模式，将自动开启
  # enabledjob: false
app:
  jwt:
    # token 密钥，生产环境时及的修改
    secret: edu/admin
    # token 过期时间 单位：秒
    timeout: 7200s
    # 头
    header: Authorization
    #
    query: token
    # 
    cookie: jwt
  gen:
    name: member
    # 代码生成读取的数据库名称
    dbname: edu_member
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../../../../../admin-ui/src
    # 后端代码生成位置
    backpath: ../../../member/internal
    # 模板
    template:
      model: ../../template/model.go.template
      dao: ../../template/dao.go.template
      js: ../../template/js.go.template
      vue: ../../template/vue.go.template
  tools:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/information_schema?charset=utf8mb4&parseTime=true
  tiku:
    path: html
