service:
  name: job
  version: v1.0.0
server:
  http:
    address: 0.0.0.0:8007
    timeout: 1s
  grpc:
    address: 0.0.0.0:9007
    timeout: 1s
  kafka:
    topic: goim-push-topic
    group: goim-push-group-job
    brokers:
      - 127.0.0.1:9092
  comet:
    routine_chan: 1024
    routine_size: 32
  room:
    batch: 20
    signal: 1s
    idle: 900s
  rabbitMq:
    address: amqp://admin:123456@my_vhost:5672/
    # address: amqp://admin:admin@192.168.21.95:5672/
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/edu_sso?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
reg:
  etcd:
    endpoints:
      - "119.27.191.44:2379"
    dialTimeout: 3s
  instance:
    zone: "sh001"
    env: "dev"
    hostname: "test1"
    appid: "service.sso"
    addrs:
      - "grpc://127.0.0.1:9102"
