// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"edu/service/sso/internal/biz"
	"edu/service/sso/internal/conf"
	"edu/service/sso/internal/dao"
	"edu/service/sso/internal/server"
	"edu/service/sso/internal/service"
	"github.com/go-kratos/etcd/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func InitApp(confService *conf.Service, confServer *conf.Server, data *conf.Data, app *conf.App, logger log.Logger, registryRegistry *registry.Registry) (*kratos.App, error) {
	daoDao, err := dao.New(data, logger)
	if err != nil {
		return nil, err
	}
	jwtUsecase, err := biz.NewJWTUsecase(app, logger, daoDao)
	if err != nil {
		return nil, err
	}
	greeterUsecase := biz.NewGreeterUsecase(daoDao, logger)
	apiService := service.NewApiService(daoDao, jwtUsecase, greeterUsecase, logger)
	adminService := service.NewAdminService(logger, daoDao, greeterUsecase, jwtUsecase)
	ssoService := service.NewSsoService(greeterUsecase, jwtUsecase)
	grpcServer := server.NewGRPCServer(confServer, logger, apiService, adminService, ssoService)
	kratosApp := newApp(confService, logger, grpcServer, registryRegistry)
	return kratosApp, nil
}
