CREATE TABLE `sys_columns` (
`column_id`  int(11) NOT NULL AUTO_INCREMENT ,
`app_id` bigint(20) unsigned NULL DEFAULT NULL ,
`table_id`  int(11) NULL DEFAULT NULL ,
`column_name`  varchar(128)  NULL DEFAULT NULL ,
`column_comment`  varchar(128)  NULL DEFAULT NULL ,
`column_type`  varchar(128)  NULL DEFAULT NULL ,
`go_type`  varchar(128)  NULL DEFAULT NULL ,
`go_field`  varchar(128)  NULL DEFAULT NULL ,
`json_field`  varchar(128)  NULL DEFAULT NULL ,
`is_pk`  varchar(4)  NULL DEFAULT NULL ,
`is_increment`  varchar(4)  NULL DEFAULT NULL ,
`is_required`  varchar(4)  NULL DEFAULT NULL ,
`is_insert`  varchar(4)  NULL DEFAULT NULL ,
`is_edit`  varchar(4)  NULL DEFAULT NULL ,
`is_list`  varchar(4)  NULL DEFAULT NULL ,
`is_query`  varchar(4)  NULL DEFAULT NULL ,
`query_type`  varchar(128)  NULL DEFAULT NULL ,
`html_type`  varchar(128)  NULL DEFAULT NULL ,
`dict_type`  varchar(128)  NULL DEFAULT NULL ,
`sort`  int(11) NULL DEFAULT NULL ,
`list`  varchar(1)  NULL DEFAULT NULL ,
`pk`  tinyint(1) NULL DEFAULT NULL ,
`required`  tinyint(1) NULL DEFAULT NULL ,
`super_column`  tinyint(1) NULL DEFAULT NULL ,
`usable_column`  tinyint(1) NULL DEFAULT NULL ,
`increment`  tinyint(1) NULL DEFAULT NULL ,
`insert`  tinyint(1) NULL DEFAULT NULL ,
`edit`  tinyint(1) NULL DEFAULT NULL ,
`query`  tinyint(1) NULL DEFAULT NULL ,
`remark`  varchar(255)  NULL DEFAULT NULL ,
`create_by`  varchar(128)  NULL DEFAULT NULL ,
`update_By`  varchar(128)  NULL DEFAULT NULL ,
`created_at`  datetime NULL DEFAULT NULL ,
`updated_at`  datetime NULL DEFAULT NULL ,
`deleted_at`  datetime NULL DEFAULT NULL ,
PRIMARY KEY (`column_id`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;
