// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: api/pms/pms.proto

package pms

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize   int32  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageIndex  int32  `protobuf:"varint,2,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	ConfigKey  string `protobuf:"bytes,3,opt,name=configKey,proto3" json:"configKey,omitempty"`
	ConfigName string `protobuf:"bytes,4,opt,name=configName,proto3" json:"configName,omitempty"`
	ConfigType string `protobuf:"bytes,5,opt,name=configType,proto3" json:"configType,omitempty"`
}

func (x *ListAlbumRequest) Reset() {
	*x = ListAlbumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumRequest) ProtoMessage() {}

func (x *ListAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumRequest.ProtoReflect.Descriptor instead.
func (*ListAlbumRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{2}
}

func (x *ListAlbumRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAlbumRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListAlbumRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *ListAlbumRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *ListAlbumRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

type ListAlbumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAlbumReply) Reset() {
	*x = ListAlbumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAlbumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumReply) ProtoMessage() {}

func (x *ListAlbumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumReply.ProtoReflect.Descriptor instead.
func (*ListAlbumReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{3}
}

type GetAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAlbumRequest) Reset() {
	*x = GetAlbumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumRequest) ProtoMessage() {}

func (x *GetAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlbumRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlbumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlbumReply) Reset() {
	*x = GetAlbumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlbumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumReply) ProtoMessage() {}

func (x *GetAlbumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumReply.ProtoReflect.Descriptor instead.
func (*GetAlbumReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{5}
}

type CreateAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAlbumRequest) Reset() {
	*x = CreateAlbumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumRequest) ProtoMessage() {}

func (x *CreateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumRequest.ProtoReflect.Descriptor instead.
func (*CreateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{6}
}

type CreateAlbumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAlbumReply) Reset() {
	*x = CreateAlbumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlbumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumReply) ProtoMessage() {}

func (x *CreateAlbumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumReply.ProtoReflect.Descriptor instead.
func (*CreateAlbumReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{7}
}

type UpdateAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAlbumRequest) Reset() {
	*x = UpdateAlbumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumRequest) ProtoMessage() {}

func (x *UpdateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{8}
}

type UpdateAlbumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAlbumReply) Reset() {
	*x = UpdateAlbumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAlbumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumReply) ProtoMessage() {}

func (x *UpdateAlbumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumReply.ProtoReflect.Descriptor instead.
func (*UpdateAlbumReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{9}
}

type DeleteAlbumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids string `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteAlbumRequest) Reset() {
	*x = DeleteAlbumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumRequest) ProtoMessage() {}

func (x *DeleteAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlbumRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAlbumRequest) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

type DeleteAlbumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAlbumReply) Reset() {
	*x = DeleteAlbumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAlbumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumReply) ProtoMessage() {}

func (x *DeleteAlbumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumReply.ProtoReflect.Descriptor instead.
func (*DeleteAlbumReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{11}
}

type ListAlbumPicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize   int32  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageIndex  int32  `protobuf:"varint,2,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	ConfigKey  string `protobuf:"bytes,3,opt,name=configKey,proto3" json:"configKey,omitempty"`
	ConfigName string `protobuf:"bytes,4,opt,name=configName,proto3" json:"configName,omitempty"`
	ConfigType string `protobuf:"bytes,5,opt,name=configType,proto3" json:"configType,omitempty"`
}

func (x *ListAlbumPicRequest) Reset() {
	*x = ListAlbumPicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAlbumPicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumPicRequest) ProtoMessage() {}

func (x *ListAlbumPicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumPicRequest.ProtoReflect.Descriptor instead.
func (*ListAlbumPicRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{12}
}

func (x *ListAlbumPicRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAlbumPicRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListAlbumPicRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *ListAlbumPicRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *ListAlbumPicRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

type ListAlbumPicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAlbumPicReply) Reset() {
	*x = ListAlbumPicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAlbumPicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlbumPicReply) ProtoMessage() {}

func (x *ListAlbumPicReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlbumPicReply.ProtoReflect.Descriptor instead.
func (*ListAlbumPicReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{13}
}

type GetAlbumPicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAlbumPicRequest) Reset() {
	*x = GetAlbumPicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlbumPicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumPicRequest) ProtoMessage() {}

func (x *GetAlbumPicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumPicRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumPicRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{14}
}

func (x *GetAlbumPicRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlbumPicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlbumPicReply) Reset() {
	*x = GetAlbumPicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlbumPicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumPicReply) ProtoMessage() {}

func (x *GetAlbumPicReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumPicReply.ProtoReflect.Descriptor instead.
func (*GetAlbumPicReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{15}
}

type CreateAlbumPicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAlbumPicRequest) Reset() {
	*x = CreateAlbumPicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlbumPicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumPicRequest) ProtoMessage() {}

func (x *CreateAlbumPicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumPicRequest.ProtoReflect.Descriptor instead.
func (*CreateAlbumPicRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{16}
}

type CreateAlbumPicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAlbumPicReply) Reset() {
	*x = CreateAlbumPicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlbumPicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumPicReply) ProtoMessage() {}

func (x *CreateAlbumPicReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumPicReply.ProtoReflect.Descriptor instead.
func (*CreateAlbumPicReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{17}
}

type UpdateAlbumPicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAlbumPicRequest) Reset() {
	*x = UpdateAlbumPicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAlbumPicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumPicRequest) ProtoMessage() {}

func (x *UpdateAlbumPicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumPicRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlbumPicRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{18}
}

type UpdateAlbumPicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAlbumPicReply) Reset() {
	*x = UpdateAlbumPicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAlbumPicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumPicReply) ProtoMessage() {}

func (x *UpdateAlbumPicReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumPicReply.ProtoReflect.Descriptor instead.
func (*UpdateAlbumPicReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{19}
}

type DeleteAlbumPicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids string `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteAlbumPicRequest) Reset() {
	*x = DeleteAlbumPicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAlbumPicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumPicRequest) ProtoMessage() {}

func (x *DeleteAlbumPicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumPicRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlbumPicRequest) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteAlbumPicRequest) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

type DeleteAlbumPicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAlbumPicReply) Reset() {
	*x = DeleteAlbumPicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pms_pms_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAlbumPicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumPicReply) ProtoMessage() {}

func (x *DeleteAlbumPicReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pms_pms_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumPicReply.ProtoReflect.Descriptor instead.
func (*DeleteAlbumPicReply) Descriptor() ([]byte, []int) {
	return file_api_pms_pms_proto_rawDescGZIP(), []int{21}
}

var File_api_pms_pms_proto protoreflect.FileDescriptor

var file_api_pms_pms_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6d, 0x73, 0x2f, 0x70, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x1a, 0x11, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a,
	0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a,
	0x09, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0xaa, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65,
	0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62,
	0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26, 0x0a, 0x12, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x62,
	0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xad, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69,
	0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69,
	0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69,
	0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d,
	0x50, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x98, 0x07, 0x0a, 0x05, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x59, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1e, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x58, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x70,
	0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17,
	0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x4c, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73,
	0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73,
	0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x14, 0x22, 0x12, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x73,
	0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x4c, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41,
	0x70, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x1a,
	0x12, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c,
	0x62, 0x75, 0x6d, 0x12, 0x5f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x62,
	0x75, 0x6d, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x2a, 0x18, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x2f, 0x7b,
	0x69, 0x64, 0x73, 0x7d, 0x12, 0x62, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x50, 0x69, 0x63, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x70, 0x69,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x12, 0x19, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c, 0x62, 0x75,
	0x6d, 0x70, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x61, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41,
	0x70, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12,
	0x1a, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c,
	0x62, 0x75, 0x6d, 0x70, 0x69, 0x63, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x55, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x12, 0x11, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63,
	0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x15, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x70,
	0x69, 0x63, 0x12, 0x55, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x50, 0x69, 0x63, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d,
	0x73, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x17, 0x1a, 0x15, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d,
	0x73, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x70, 0x69, 0x63, 0x12, 0x68, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x12, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x70, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x2a, 0x1b, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x6d, 0x73, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x70, 0x69, 0x63, 0x2f, 0x7b, 0x69,
	0x64, 0x73, 0x7d, 0x32, 0x98, 0x02, 0x0a, 0x03, 0x41, 0x70, 0x69, 0x12, 0x53, 0x0a, 0x0b, 0x53,
	0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x55, 0x52, 0x4c, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6d, 0x73, 0x2f, 0x73, 0x61, 0x79, 0x5f, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x12, 0x5e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x6d, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6d, 0x73, 0x2f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x5c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1e,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6d, 0x73, 0x2f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x1c,
	0x0a, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6d, 0x73, 0x50, 0x01, 0x5a, 0x0f, 0x65, 0x64, 0x75,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6d, 0x73, 0x3b, 0x70, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pms_pms_proto_rawDescOnce sync.Once
	file_api_pms_pms_proto_rawDescData = file_api_pms_pms_proto_rawDesc
)

func file_api_pms_pms_proto_rawDescGZIP() []byte {
	file_api_pms_pms_proto_rawDescOnce.Do(func() {
		file_api_pms_pms_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pms_pms_proto_rawDescData)
	})
	return file_api_pms_pms_proto_rawDescData
}

var file_api_pms_pms_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_pms_pms_proto_goTypes = []interface{}{
	(*HelloReq)(nil),              // 0: api.pms.HelloReq
	(*HelloResp)(nil),             // 1: api.pms.HelloResp
	(*ListAlbumRequest)(nil),      // 2: api.pms.ListAlbumRequest
	(*ListAlbumReply)(nil),        // 3: api.pms.ListAlbumReply
	(*GetAlbumRequest)(nil),       // 4: api.pms.GetAlbumRequest
	(*GetAlbumReply)(nil),         // 5: api.pms.GetAlbumReply
	(*CreateAlbumRequest)(nil),    // 6: api.pms.CreateAlbumRequest
	(*CreateAlbumReply)(nil),      // 7: api.pms.CreateAlbumReply
	(*UpdateAlbumRequest)(nil),    // 8: api.pms.UpdateAlbumRequest
	(*UpdateAlbumReply)(nil),      // 9: api.pms.UpdateAlbumReply
	(*DeleteAlbumRequest)(nil),    // 10: api.pms.DeleteAlbumRequest
	(*DeleteAlbumReply)(nil),      // 11: api.pms.DeleteAlbumReply
	(*ListAlbumPicRequest)(nil),   // 12: api.pms.ListAlbumPicRequest
	(*ListAlbumPicReply)(nil),     // 13: api.pms.ListAlbumPicReply
	(*GetAlbumPicRequest)(nil),    // 14: api.pms.GetAlbumPicRequest
	(*GetAlbumPicReply)(nil),      // 15: api.pms.GetAlbumPicReply
	(*CreateAlbumPicRequest)(nil), // 16: api.pms.CreateAlbumPicRequest
	(*CreateAlbumPicReply)(nil),   // 17: api.pms.CreateAlbumPicReply
	(*UpdateAlbumPicRequest)(nil), // 18: api.pms.UpdateAlbumPicRequest
	(*UpdateAlbumPicReply)(nil),   // 19: api.pms.UpdateAlbumPicReply
	(*DeleteAlbumPicRequest)(nil), // 20: api.pms.DeleteAlbumPicRequest
	(*DeleteAlbumPicReply)(nil),   // 21: api.pms.DeleteAlbumPicReply
	(*Album)(nil),                 // 22: api.pms.Album
	(*AlbumPic)(nil),              // 23: api.pms.AlbumPic
	(*ApiReply)(nil),              // 24: api.pms.ApiReply
}
var file_api_pms_pms_proto_depIdxs = []int32{
	2,  // 0: api.pms.Admin.ListAlbum:input_type -> api.pms.ListAlbumRequest
	4,  // 1: api.pms.Admin.GetAlbum:input_type -> api.pms.GetAlbumRequest
	22, // 2: api.pms.Admin.CreateAlbum:input_type -> api.pms.Album
	22, // 3: api.pms.Admin.UpdateAlbum:input_type -> api.pms.Album
	10, // 4: api.pms.Admin.DeleteAlbum:input_type -> api.pms.DeleteAlbumRequest
	12, // 5: api.pms.Admin.ListAlbumPic:input_type -> api.pms.ListAlbumPicRequest
	14, // 6: api.pms.Admin.GetAlbumPic:input_type -> api.pms.GetAlbumPicRequest
	23, // 7: api.pms.Admin.CreateAlbumPic:input_type -> api.pms.AlbumPic
	23, // 8: api.pms.Admin.UpdateAlbumPic:input_type -> api.pms.AlbumPic
	20, // 9: api.pms.Admin.DeleteAlbumPic:input_type -> api.pms.DeleteAlbumPicRequest
	0,  // 10: api.pms.Api.SayHelloURL:input_type -> api.pms.HelloReq
	2,  // 11: api.pms.Api.ListAlbum:input_type -> api.pms.ListAlbumRequest
	4,  // 12: api.pms.Api.GetAlbum:input_type -> api.pms.GetAlbumRequest
	24, // 13: api.pms.Admin.ListAlbum:output_type -> api.pms.ApiReply
	24, // 14: api.pms.Admin.GetAlbum:output_type -> api.pms.ApiReply
	24, // 15: api.pms.Admin.CreateAlbum:output_type -> api.pms.ApiReply
	24, // 16: api.pms.Admin.UpdateAlbum:output_type -> api.pms.ApiReply
	24, // 17: api.pms.Admin.DeleteAlbum:output_type -> api.pms.ApiReply
	24, // 18: api.pms.Admin.ListAlbumPic:output_type -> api.pms.ApiReply
	24, // 19: api.pms.Admin.GetAlbumPic:output_type -> api.pms.ApiReply
	24, // 20: api.pms.Admin.CreateAlbumPic:output_type -> api.pms.ApiReply
	24, // 21: api.pms.Admin.UpdateAlbumPic:output_type -> api.pms.ApiReply
	24, // 22: api.pms.Admin.DeleteAlbumPic:output_type -> api.pms.ApiReply
	1,  // 23: api.pms.Api.SayHelloURL:output_type -> api.pms.HelloResp
	3,  // 24: api.pms.Api.ListAlbum:output_type -> api.pms.ListAlbumReply
	5,  // 25: api.pms.Api.GetAlbum:output_type -> api.pms.GetAlbumReply
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_pms_pms_proto_init() }
func file_api_pms_pms_proto_init() {
	if File_api_pms_pms_proto != nil {
		return
	}
	file_api_pms_api_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_pms_pms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAlbumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAlbumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlbumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlbumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlbumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlbumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAlbumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAlbumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAlbumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAlbumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAlbumPicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAlbumPicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlbumPicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlbumPicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlbumPicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlbumPicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAlbumPicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAlbumPicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAlbumPicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pms_pms_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAlbumPicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pms_pms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_pms_pms_proto_goTypes,
		DependencyIndexes: file_api_pms_pms_proto_depIdxs,
		MessageInfos:      file_api_pms_pms_proto_msgTypes,
	}.Build()
	File_api_pms_pms_proto = out.File
	file_api_pms_pms_proto_rawDesc = nil
	file_api_pms_pms_proto_goTypes = nil
	file_api_pms_pms_proto_depIdxs = nil
}
