// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"edu/service/oms/internal/biz"
	"edu/service/oms/internal/conf"
	"edu/service/oms/internal/server"
	"edu/service/oms/internal/service"
	"github.com/go-kratos/etcd/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func InitApp(confService *conf.Service, confServer *conf.Server, app *conf.App, logger log.Logger, registryRegistry *registry.Registry) (*kratos.App, error) {
	apiService := service.NewApiService()
	greeterUsecase := biz.NewGreeterUsecase(app, logger)
	adminService := service.NewAdminService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, logger, apiService, adminService)
	kratosApp := newApp(confService, logger, grpcServer, registryRegistry)
	return kratosApp, nil
}
