service:
  name: member
  version: v1.0.0
server:
  http:
    address: 0.0.0.0:8006
    timeout: 1s
  grpc:
    address: 0.0.0.0:9006
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/edu_member?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
  migrate:
    path: file://../../migrations
reg:
  etcd:
    endpoints:
      - "127.0.0.1:2379"
    dialTimeout: 3s
app:
  uuid:
    # 机器ID
    machine_id: 1
